### ISSUE TITLE
additional interfaces are absent in rendered template while using preseed_networking_setup

### ISSUE THREAD

**Issue by rmallah** [theforeman/community-templates#253]
Steps to replicate:
In my case 
1) Created a VM with two network interfaces.
2) used fdi version 3.0 to discover the VM booted via PXE
3) initiated "Provision" of the new host 
4) in interface section the 2 interfaces are displayed 
5) both the interface were edited to relevant value.
6) provisioning form was submitted.

the YAML in the host screen reads below and there is no reference to the additional interface.

```

---
classes: {}
parameters:
  puppetmaster: foremanserver.XXXXXXXXXXXXX.com
  domainname: ''
  hostgroup: Provision from foremanserver.XXXXXXXXX.com
  root_pw: "$5$z5OS7cOG$SOXTFKS42JDGVTMb11SxBcHMm0G9lRHNiZLWOBmowR."
  puppet_ca: foremanserver.XXXXXXXXXXX.com
  foreman_env: production
  owner_name: Admin User
  owner_email: root@XXXXXXXX.com
  foreman_subnets:
  - network: 172.16.0.0
    mask: 255.255.0.0
    name: adminpxe
    vlanid: ''
    gateway: 172.16.10.1
    dns_primary: 172.16.10.2
    dns_secondary: ''
    from: 172.16.10.20
    to: 172.16.10.250
    boot_mode: DHCP
    ipam: DHCP
  foreman_interfaces:
  - mac: 52:54:00:f1:8a:5b
    ip: 172.16.10.128
    type: Interface
    name: mac525400f18a5b.XXXXXXXXXX.com
    attrs:
      network: 172.16.0.0
      netmask: 255.255.0.0
      mtu: '1500'
    virtual: false
    link: true
    identifier: eth0
    managed: true
    primary: true
    provision: true
    subnet:
      network: 172.16.0.0
      mask: 255.255.0.0
      name: adminpxe
      vlanid: ''
      gateway: 172.16.10.1
      dns_primary: 172.16.10.2
      dns_secondary: ''
      from: 172.16.10.20
      to: 172.16.10.250
      boot_mode: DHCP
      ipam: DHCP
  - mac: 52:54:00:43:8d:72
    ip: 
    type: Interface
    name: ''
    attrs:
      mtu: '1500'
    virtual: false
    link: true
    identifier: eth1
    managed: false
    primary: false
    provision: false
    subnet:
      network: 172.16.0.0
      mask: 255.255.0.0
      name: adminpxe
      vlanid: ''
      gateway: 172.16.10.1
      dns_primary: 172.16.10.2
      dns_secondary: ''
      from: 172.16.10.20
      to: 172.16.10.250
      boot_mode: DHCP
      ipam: DHCP
  http-proxy: foremanserver.XXXXXXXXXXX.com
  http-proxy-port: '3128'
environment: production

```
